[package]
name = "bayes_filter"
version = "0.1.0"
authors = ["Michael Stevens <mail@michael-stevens.de>"]
edition = "2018"

[dependencies]
nalgebra = {path ="../nalgebra"}
approx = "0.3.2"

[lib]
name = "bayes_filter"
path = "src/lib.rs"
